###GET HELLO
GET http://localhost:3000

###GET Detail
GET http://localhost:3001/api/user/me/balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOltdLCJwZXJtaXNzaW9uIjpbXSwiaWF0IjoxNzY1NTI1MjI2LCJleHAiOjE3NjYxMzAwMjZ9.wiTlKr5GSXVNU8EM4xRYi7rMXMxaEaF7VWLeST92YfM

###LOGIN
POST http://localhost:3001/auth/login
Content-Type: application/json

{ 
    "email": "newuser1@email.com",
    "password_hash": "$2b$10$hashedpassword_example"
}

### REGISTER
POST http://localhost:3001/api/user
Content-Type: application/json

{
  "email": "newuser1@email.com",
  "password_hash": "$2b$10$hashedpassword_example",
  "first_name": "New",
  "last_name": "User",
  "phone": "09876543212"
}


### get user
GET http://localhost:3001/api/user
Content-Type: application/json

### get user by id
GET http://localhost:3001/api/user/detail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjIsInJvbGUiOltdLCJwZXJtaXNzaW9uIjpbXSwiaWF0IjoxNzY1NTE5NTA2LCJleHAiOjE3NjU1MjA0MDZ9.Pwtjo7GUQPODuumK5Y0JU9XkAAAe_gZdm6Gy5wlIMMM


### delete user
DELETE http://localhost:3000/api/user/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGVtYWlsLmNvbSIsInN1YiI6MywiaWF0IjoxNzU4Nzg3Mzc1LCJleHAiOjE3NTg3ODc0MzV9.-wpqInrbV6TnqVK3zzxr_vtLB3G1EBxlzs2SP0f4Vy0